### ISSUE TITLE
dmesg | grep avt is not working and ls /dev/video* not found

### ISSUE THREAD

**Issue by imharish63** [alliedvision/linux_nvidia_jetson#29] opened 2021-10-31 18:56 UTC
from the below thread:
https://github.com/alliedvision/linux_nvidia_jetson/issues/13#issuecomment-775764784

i am using Method C : Cross-compile binaries from source

on my machine ls /dev/video* not working so i tried dmesg | grep avt

and i dont get any output 
and output is like this

![dmesg |grep](https://user-images.githubusercontent.com/59102921/139597409-44dd8cd1-07d9-427c-a93d-5531ba1c237d.png)

i dont know how to proceed futher. kindly help me

@AVTechie
@BernardoLuck

**Comment by arunprakash-avt** [comment] 2021-12-01 10:55
As I check above linked issue . You have used the Jetpack 4.4.DP version now we have Jetpack 4.5.1 so I request you to use the SDK manager in a linux host system and update the System on Module to Jetpack 4.5.1 . **For installation of the camera Drivers on jetpack 4.5.1 please follow our Github.**

**Comment by arunprakash-avt** [comment] 2021-12-01 10:57
For further support, I request you to write us an email to support@alliedvision.com.

**Comment by imharish63** [comment] 2021-12-02 14:44
@arunprakash-avt 
thanks for your reply. But i already contacted allied vision for instructions and its working now

**Comment by arunprakash-avt** [comment] 2021-12-02 14:48
As the issue is solved I request you to close it. As it helps our further process.

**Closed** 2022-04-08 09:02 UTC
